# NOTE: The autoloading feature works with image phpswoole/swoole:latest (or phpswoole/swoole in short)
# and phpswoole/swoole:latest-dev only. For any other image, you need to use it as a base image and install package
# inotify-tools first to make it work, like
#
#    FROM phpswoole/swoole:4.4.6-php7.3
#
#    RUN \
#        apt-get update                   && \
#        apt-get install -y inotify-tools && \
#        rm -r /var/lib/apt/lists/*
#
version: '3'

services:
  app:
    image: phpswoole/swoole
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
    ports:
      - 80:9501
    volumes:
      - ./rootfilesystem/var/www:/var/www
