# This docker-compose.yml file shows how Supervisor program(s) are reloaded automatically when file changes detected
# under web root /var/www. There are two environment variables used:
#     1. AUTORELOAD_PROGRAMS: space-separated Supervisor program(s) to be reloaded when file changes detected. e.g.,
#            AUTORELOAD_PROGRAMS: "swoole"       # Autoreload Supervisor program "swoole" only.
#            AUTORELOAD_PROGRAMS: "swoole nginx" # Autoreload Supervisor program "swoole" and "nginx".
#     2. AUTORELOAD_ALL_FILES: If set to "true", "1", "yes", or "y", reload Supervisor program(s) when any file under
#        the root directory (/var/www in this example) is changed; otherwise, reload only when PHP file(s) are changed.
#
# NOTE: The autoreloading feature works with image phpswoole/swoole:latest (or phpswoole/swoole in short)
# and phpswoole/swoole:latest-dev only. For any other image, you need to use it as a base image and install package
# inotify-tools first to make it work, like
#
#    FROM phpswoole/swoole:4.4.6-php7.3
#
#    RUN \
#        apt-get update                   && \
#        apt-get install -y inotify-tools && \
#        rm -r /var/lib/apt/lists/*
#
version: '3'

services:
  app:
    image: phpswoole/swoole
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ALL_FILES: 0
    ports:
      - 80:9501
    volumes:
      - ./rootfilesystem/var/www:/var/www
