language: php

php:
  - 7.3

services:
  - docker

env:
  - PHP_VERSION=7.1 ARCHITECTURE=amd64
  - PHP_VERSION=7.2 ARCHITECTURE=amd64
  - PHP_VERSION=7.3 ARCHITECTURE=amd64
  - PHP_VERSION=7.1 ARCHITECTURE=arm64v8
  - PHP_VERSION=7.2 ARCHITECTURE=arm64v8
  - PHP_VERSION=7.3 ARCHITECTURE=arm64v8

matrix:
  fast_finish: true
  allow_failures:
    - env: PHP_VERSION=7.1 ARCHITECTURE=arm64v8
    - env: PHP_VERSION=7.2 ARCHITECTURE=arm64v8
    - env: PHP_VERSION=7.3 ARCHITECTURE=arm64v8

before_install:
  - composer update -n
  - ./bin/generate-dockerfiles.php ${TRAVIS_BRANCH%%-*} || true
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build_version_based_images
      if: branch =~ /^[1-9]\d*\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-\w+)?$/
      script: ./bin/build.sh
    - stage: build_latest_image
      if: branch = master
      script: ./bin/build.sh
      env: PHP_VERSION=7.3 ARCHITECTURE=amd64
