language: php

php:
  - 7.3

services:
  - docker

env:
  - ARCHITECURE="amd64"

if: branch =~ /^[1-9]\d*\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-\w+)?$/

before_install:
  - composer update -n

script:
  - ./bin/generate-docker-files.php ${TRAVIS_BRANCH%%-*}
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./bin/build.sh ${ARCHITECURE}
