language: php

php:
  - 7.3

services:
  - docker

env:
  - DEV_MODE=false
  - DEV_MODE=true

matrix:
  fast_finish: true

before_install:
  - composer update -n
  - ./bin/generate-dockerfiles.php ${TRAVIS_BRANCH%%-*} || true
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: test
      if: branch =~ /^[1-9]\d*\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-\w+)?$/
      script: ./bin/build.sh
      env: PHP_VERSION=7.1 ARCHITECTURE=amd64
    - stage: test
      if: branch =~ /^[1-9]\d*\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-\w+)?$/
      script: ./bin/build.sh
      env: PHP_VERSION=7.2 ARCHITECTURE=amd64
    - stage: test
      if: branch =~ /^[1-9]\d*\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-\w+)?$/
      script: ./bin/build.sh
      env: PHP_VERSION=7.3 ARCHITECTURE=amd64
    - script: ./vendor/bin/phpcs --standard=PSR12 bin/generate-dockerfiles.php src tests
      if: branch = master AND env(DEV_MODE) = false
    - script: ./vendor/bin/phpunit
      if: branch = master AND env(DEV_MODE) = false
    - stage: build_latest_image
      if: branch = master
      script: ./bin/build.sh
      env: PHP_VERSION=7.3 ARCHITECTURE=amd64
