# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:4.4.4.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - 7.1.31
  - 7.2.21
  - 7.3.8
image:
  composer:
    version: 1.9.0
  swoole_extensions:
    async:
      version: "6df15d51f9edd9950c418f2374d0b97fce08a30b"
      enabled: true
    orm:
    postgresql:
      version: "aaf984b75da3a34aac62d931b517c6d2055f7881"
    serialize:
      enabled: true
