# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:4.4.16.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "released"
php:
  - "7.1.33"
  - "7.2.28"
  - "7.3.15"
  - "7.4.3"
image:
  composer:
    version: "1.9.3"
