# The YAML configuration file for generating Dockerfile of image phpswoole/swoole.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - 7.3
image:
  composer:
    version: 1.9.0
  inotify: true
  swoole_extensions:
    # async:
      # version: "8030b9550f64ebb64ce64b6a5f8a0f19dcdc4960"
      # enabled: true
    orm:
      enabled: true
    postgresql:
      # version: "aaf984b75da3a34aac62d931b517c6d2055f7881"
      enabled: true
    serialize:
      enabled: true
